### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by alexnest-ua** [MHProDev/PyRoxy#10]
Traceback (most recent call last):
  File "runner.py", line 12, in <module>
    from MHDDoS.start import ProxyManager, logger
  File "/home/azureuser/mhddos_proxy/MHDDoS/start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], chr] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length)
                                                                                      ^
SyntaxError: invalid syntax

Because of last commit in PyProxy: https://github.com/MHProDev/PyRoxy/commit/ffecf3fb67306172e6e0444e851093a059bf12c1

**Comment by MHProDev** [comment]
fixed in last commit
