### ISSUE TITLE
Invalid syntax with python 3.9

### ISSUE THREAD

**Issue by sergiy-kozak** [MHProDev/PyRoxy#11]
```
$ python --version
Python 3.9.5
$ python -c "import PyRoxy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.virtualenvs/botnet-dds/lib/python3.9/site-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "/home/ubuntu/.virtualenvs/botnet-dds/lib/python3.9/site-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], chr] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length)
                                                                                      ^
SyntaxError: invalid syntax
```

To be honest, it's difficult to understand what code is meant to be in that line. There is no usage of `rand_char()` across all sources.

**Comment by alexnest-ua** [comment]
Because of last commit in PyProxy: https://github.com/MHProDev/PyRoxy/commit/ffecf3fb67306172e6e0444e851093a059bf12c1

**Comment by deveArt** [comment]
Made a pull. Still getting this error.

**Comment by MHProDev** [comment]
fixed in last commit
